
#ifndef _GFT_H_
#define _GFT_H_

#include "gft_common.h"
#include "gft_adjrel.h"
#include "gft_gpqueue_by_Falcao.h"
#include "gft_morphology.h"
#include "gft_arraylist.h"
#include "gft_heap.h"
#include "gft_heap32.h"
#include "gft_heap64f.h"
#include "gft_heap_lex.h"
#include "gft_heap32fi_lex.h"
#include "gft_heap32fif_lex.h"
#include "gft_heap32fifi_lex.h"
#include "gft_heappair.h"
#include "gft_ift.h"
#include "gft_image64.h"
#include "gft_string.h"
#include "gft_cimage.h"
#include "gft_cimage32f.h"
#include "gft_filelist.h"
#include "gft_queue.h"
#include "gft_color.h"
#include "gft_highlight.h"
#include "gft_image32.h"
#include "gft_image32f.h"
#include "gft_imagegraph.h"
#include "gft_graph.h"
#include "gft_layeredgraph.h"
#include "gft_filtering.h"
#include "gft_evaluation.h"
#include "gft_radiometric.h"
#include "gft_analysis.h"
#include "gft_marker.h"
#include "gft_attributelist.h"
#include "gft_configfile.h"
#include "gft_geometry.h"
#include "gft_draw.h"

#include "gft_matrix.h"
#include "gft_bmap.h"
#include "gft_set.h"
#include "gft_stack.h"
#include "gft_pqueue32.h"
#include "gft_pqueue16.h"
#include "gft_hashtable.h"
#include "gft_curve.h"


#endif

